[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore AttendBackend/AttendBackend.csproj",
  "dotnet publish AttendBackend/AttendBackend.csproj -c Release -o out"
]

[phases.start]
cmd = "dotnet out/AttendBackend.dll"