services:
  - type: web
    name: attend
    env: web
    buildCommand: dotnet build AttendBackend/AttendBackend.csproj
    startCommand: dotnet AttendBackend/bin/Debug/net8.0/AttendBackend.dll
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Server=CAIROGHOULPC\\SQLEXPRESS;Database=AttendDb;User ID=sqladmin;password=AttendDB123;Trusted_Connection=True;TrustServerCertificate=True;"
    plan: free
    branch: main
    rootDirectory: AttendBackend
